export const professions = [
  { name: "Programador" },
  { name: "Plomero" },
  { name: "Electricista" },
  { name: "Programador" },
  { name: "Plomero" },
  { name: "Electricista" },
  { name: "Programador" },
  { name: "Plomero" },
  { name: "Electricista" },
  { name: "Programador" },
  { name: "Plomero" },
  { name: "Electricista" },
  { name: "Programador" },
  { name: "Plomero" },
  { name: "Electricista" },
  { name: "Programador" },
  { name: "Plomero" },
  { name: "Electricista" },
];
